title: Shubham Malik 
logo: "/images/profilepic.jpg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with about 6 months of experience, is aspiring for a challenging environment to foster professional and personal growth!
  <br><br>
  Gold medallist during thr final year of BSc(H) Mathematics at the Unversity of Delhi!
  <br><br>
  <a href="https://https://www.linkedin.com/in/shubhamalik2000/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics:  # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
